## Cosine Works!!!

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

sentences = [
    "I want to book a flight to Delhi",
    "Help me reserve a plane ticket to Delhi",
    "What is the capital of France?"
]

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(sentences)

cos_sim = cosine_similarity(X)

print(cos_sim)

[[1.         0.28809809 0.        ]
 [0.28809809 1.         0.        ]
 [0.         0.         1.        ]]


## Cosine FAILS (Repetition)

In [8]:
sentences = [
    "Error occurred",
    "Error occurred error occurred error occurred error occurred"
]

vectorizer = TfidfVectorizer(use_idf=False)
X = vectorizer.fit_transform(sentences)

cos_sim = cosine_similarity(X)

print(cos_sim)

[[1. 1.]
 [1. 1.]]


### Dot Product Works here

In [18]:
import numpy as np

vectorizer = TfidfVectorizer(use_idf=False,norm=None)
X = vectorizer.fit_transform(sentences)


dot = (X @ X.T).toarray()

print("\nCosine similarity:")
print(cosine_similarity(X))


print("\nDot product:")
print((X @ X.T).toarray())


Cosine similarity:
[[1.         0.70710678]
 [0.70710678 1.        ]]

Dot product:
[[3. 3.]
 [3. 6.]]


## Cosine FAILS (opposite meaning, same words)

In [12]:
sentences = [
    "This medicine is effective",
    "This medicine is not effective"
]

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(sentences)

print(cosine_similarity(X))

[[1.         0.81818021]
 [0.81818021 1.        ]]


## Cosine FAILS (keyword overload)

In [14]:
sentences = [
    "apple banana car",
    "apple banana car train phone laptop"
]

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(sentences)

print(cosine_similarity(X))

[[1.         0.57973867]
 [0.57973867 1.        ]]


### Jaccards works better here

In [15]:
set1 = set(sentences[0].split())
set2 = set(sentences[1].split())

jaccard = len(set1 & set2) / len(set1 | set2)
print(jaccard)

0.5
